swagger: '2.0'
info:
  title: "BoilerPlate GW Swagger"
  version: 0.0.1
consumes:
  - application/json
produces:
  - application/json
paths:
  /data/{id}:
    get:
      operationId: Data
      responses:
        '200':
          description: 'A successful response.'
          schema:
            $ref: '#/definitions/Data'
        '500':
          description: 'Error response'
          schema: 
            $ref: '#/definitions/ApiInvalidResponse'
        '404':
          description: 'data not found'
          schema: 
            $ref: '#/definitions/ApiInvalidResponse'            
              
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: 'id of a record'
           
      tags:
        - Data

definitions:
  Data:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  
  ApiInvalidResponse:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
